name: cltxpj
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  easy_localization: ^3.0.7
  shared_preferences: ^2.5.3
  flutter_local_notifications: ^18.0.1
  url_launcher: ^6.3.1
  timezone: ^0.10.1
  provider: ^6.1.5
  flutter_secure_storage: ^9.2.4
  flutter_dotenv: ^5.2.1
  flutter_svg: ^2.1.0
  getwidget: ^6.0.0
  intl: ^0.19.0
  fl_chart: ^1.0.0
  flutter_masked_text2: ^0.9.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true

  assets:
  - assets/
  - assets/translations/
  - assets/icons/